version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-java
    environment:
      POSTGRES_DB: empresa
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d empresa"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  java-app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/empresa
      DB_USER: admin
      DB_PASSWORD: admin

volumes:
  postgres_data:
